### PR TITLE
Refactor calculate coordinates function

### PR DESCRIPTION
**Pull request by parkerbjur**
I have refactored calculateCoordinates function to make it a bit simpler. I also added the ability to define an arbitrary rotation angle. Currently I just pass 0 rad or pi/6 rad to do the "flat" or "pointy" hexes.

### CODE REVIEW

**Comment by tieje** [comment]
Thanks for the documentation. All checks have passed.
However, do you mind writing a test for the calculateCoordinates function since that's the one that was changed?

**Comment by parkerbjur** [comment]
Ya, I can write a test for it. Do you want me to submit that as a separate PR or resubmit it all together?

**Comment by tieje** [comment]
Alotegther is fine.

**Comment by tieje** [comment]
per our discord discussion for record-keeping:
"I'm going to accept your PR. When I last made my suggestion for testing, I didn't really know how testing occurred for Layout yet. It's just refactoring and getting the same output so if the current tests pass, then I think we're in the clear.
Though the rewire package (https://github.com/jhnns/rewire) might be helpful for testing private functions. I guess you'll want to make a separate branch for it, if you want to implement testing. I'll put a post in dev discussions about potentially using rewire, since I've never used it."

**Pull request merged**
