### PR TITLE
Feature/add optional class names to hexen

### PR DESCRIPTION
**Pull request by davesag**
Hi Hannu,

Please see the attached PR.  I've updated the `HexShape` class so that if you provide a `className` in the `Hex` properties it will carry that through and apply it as an additional className within the `g` element of the SVG.

I manually constructed my board as follows

    constructBoard() {
      return [
        new Hex(0,  1, -1, {className: 'edge'}),
        new Hex(0,  2, -2, {className: 'edge'}),
        new Hex(1,  0, -1, {className: 'outer'}),
        new Hex(1,  1, -2, {className: 'edge'}),
        new Hex(1,  2, -3, {className: 'outer'}),
        new Hex(2, -1, -1, {className: 'inner'}),
        new Hex(2,  0, -2, {className: 'outer'}),
        new Hex(2,  1, -3, {className: 'outer'}),
        new Hex(2,  2, -4, {className: 'inner'}),
        new Hex(3, -1, -2, {className: 'inner'}),
        new Hex(3,  0, -3, {className: 'outer'}),
        new Hex(3,  1, -4, {className: 'inner'}),
        new Hex(4, -2, -2, {className: 'start'}),
        new Hex(4, -1, -3, {className: 'inner'}),
        new Hex(4,  0, -4, {className: 'inner'}),
        new Hex(4,  1, -5, {className: 'start'}),
        new Hex(5, -2, -3, {className: 'start'}),
        new Hex(5, -1, -4, {className: 'inner'}),
        new Hex(5,  0, -5, {className: 'start'}),
        new Hex(6, -2, -4, {className: 'centre'}),
        new Hex(6, -1, -5, {className: 'centre'}),
        new Hex(7, -3, -4, {className: 'start'}),
        new Hex(7, -2, -5, {className: 'inner'}),
        new Hex(7, -1, -6, {className: 'start'}),
        new Hex(8, -4, -4, {className: 'start'}),
        new Hex(8, -3, -5, {className: 'inner'}),
        new Hex(8, -2, -6, {className: 'inner'}),
        new Hex(8, -1, -7, {className: 'start'}),
        new Hex(9, -4, -5, {className: 'inner'}),
        new Hex(9, -3, -6, {className: 'outer'}),
        new Hex(9, -2, -7, {className: 'inner'}),
        new Hex(10, -5, -5, {className: 'inner'}),
        new Hex(10, -4, -6, {className: 'outer'}),
        new Hex(10, -3, -7, {className: 'outer'}),
        new Hex(10, -2, -8, {className: 'inner'}),
        new Hex(11, -5, -6, {className: 'outer'}),
        new Hex(11, -4, -7, {className: 'edge'}),
        new Hex(11, -3, -8, {className: 'outer'}),
        new Hex(12, -5, -7, {className: 'edge'}),
        new Hex(12, -4, -8, {className: 'edge'})
      ]
    }

and using the Sass as follows:

    svg {
      g {
        fill: #00AFB0;
        fill-opacity: 0.6;
        &:hover {
          fill-opacity: 1;
          text {
            fill-opacity: 1;
            fill: #fff;
          }
        }
        polygon {
          stroke: #3F51B5;
          stroke-width: 0.2;
          transition: fill-opacity .2s;
        }
        text {
          font-family: monospace;
          font-size: 0.15em;
          fill: #000;
          fill-opacity: 0.9;
          transition: fill-opacity .2s;
        }
        &.edge {
          fill: #ede2fe;
        }
        &.outer {
          fill: #eafec9;
        }
        &.inner {
          fill: #bbfee2;
        }
        &.start {
          fill: #80b281;
        }
        &.centre {
          fill: #a5ffe5;
        }
      }
      path {
        fill: none;
        stroke: hsl(60, 20%, 70%);
        stroke-width: 0.4em;
        stroke-opacity: 0.3;
        stroke-linecap: round;
        stroke-linejoin: round;
      }
    }

with the following result.

screen shot 2017-02-11 at 1 20 25 pm

I also fixed a typo in the README and took the liberty of tightening up the use of some `var`s, `let`s, and `const`s

### CODE REVIEW

**Comment by davesag** [comment]
Update: I figured out the scaling issue I was having and have updated this PR to also support the optional supplying of a `viewBox` property to the `HexGrid` component.

**Comment by Hellenic** [comment]
Hey!
Awesome job man! Looks great, and I like the code style. Looks very much something that I would write. All the vars and stuff looks like from time when I was still getting into ES6 :D

Do you think classnames dependency is necessary? I guess it doesn't add too much size to the library but considering if it's used only for that, maybe just use something more manual for now. Thoughts?

**Comment by davesag** [comment]
Hey Hannu,

The ClassNames lib is tiny and worth including I feel. If you really don't want it I'm okay to remove it however. 

Cheers 

Dave

**Comment by Hellenic** [comment]
That's true, can probably use it for other purposes later on as well. I'll go ahead and merge this, thanks again!

Was there something else you were still working on or having problems with?

**Comment by davesag** [comment]
Awesome.  Let me know when the new version hits `npm` — I may do some more PRs as I find stuff I need for my game. Thanks for accepting the PR

**Comment by Hellenic** [comment]
There's a new version now in NPM, including your changes and some other internal refactoring. Also one more example in the repo

**Pull request merged**
