### PR TITLE
use new react context

### PR DESCRIPTION
**Pull request by IcculusC**
should be squashed if you decide to accept the PR

### CODE REVIEW

**Comment by Hellenic** [comment]
Hey! Thanks a lot. Totally missed this one.
Looks like nice updates. I'll try to dig in to this during upcoming holidays and try it out!

**Comment by IcculusC** [comment]
@Hellenic hehe I actually forked the repo and refactored everything, if you'd like to take a look at that you might be interested in adopting some of the stuff I did.  I basically wanted something more robust with much larger maps, although I never got there before I got distracted.  It's got some basic concepts that are generally more modern React, as well as a totally different paradigm for rendering things(at least in my most recent branch).  I also included hover, selection, tile metadata, and some other candy.  https://github.com/icculusc/react-hex-engine

**Comment by isaacbatst** [comment]
Hello @Hellenic ! Are you alright? Do you have the intent to merge this? Meanwhile, I published [here](https://www.npmjs.com/package/react-hexgrid-with-context-api) a temporary package with this.

**Comment by isaacbatst** [comment]
@IcculusC didn't use the package you provided, because it came with some errors, just seemed easier to do like I did.

**Comment by nearwood** [comment]
Wow, I just published [a package](https://www.npmjs.com/package/@nearwood/react-hexgrid) as well.

I didn't see this PR though, that would have saved me some time.

**Comment by Hellenic** [comment]
Oh wow. First of all, thanks for the contribution! Sorry that you've had to publish another packages.
As it's probably obvious I haven't had time for this library and probably won't.

However, I'm happy to share publishing rights to the npm, and you as collaborators to the repo if you wish?

**Comment by jannikbuschke** [comment]
There is a new version 2.0.0-beta.2 which uses the context api. Closing this for now

**Pull request closed without merging**
